### ISSUE TITLE
trouble running tests

### ISSUE THREAD

**Issue by Nejat** [async-raft/async-raft#68] opened 2020-09-02 13:19 UTC
I could not find specific compile instructions in the documentation, did I miss something?

Running ```cargo test``` causes the following compiler error when it gets to ```memstore```

```
   ...
   Compiling tracing-subscriber v0.2.11
   Compiling memstore v0.1.0 (C:\Users\nejat\repos\rust-foss\async-raft\memstore)
error: reached the type-length limit while instantiating `std::future::from_generator::<[s...]>>, ()}]>}]>>, ()}]>}]>>, ()}]>`
  --> C:\Users\nejat\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libcore\future\mod.rs:59:1
   |
59 | / pub const fn from_generator<T>(gen: T) -> impl Future<Output = T::Return>
60 | | where
61 | |     T: Generator<ResumeTy, Yield = ()>,
62 | | {
...  |
85 | |     GenFuture(gen)
86 | | }
   | |_^
   |
   = note: consider adding a `#![type_length_limit="2170465"]` attribute to your crate

error: aborting due to previous error

error: could not compile `async-raft`.
```

I have tried it with the following three targets, both ```master``` and ```0.5.0```

**Windows 10**
```
stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc
```

**Ubuntu 20.04 Distro WSL2**
```
stable-x86_64-unknown-linux-gnu
```

Thanks for the help

**Comment by thedodd** [comment] 2020-09-02 14:14
@Nejat what version of of rustc/cargo are you using?

**Comment by Nejat** [comment] 2020-09-02 14:16
```rustc 1.46.0 (04488afe3 2020-08-24)```
```cargo 1.46.0 (149022b1d 2020-07-17)```

**Comment by thedodd** [comment] 2020-09-02 14:19
Stable, beta, or nightly?

**Comment by Nejat** [comment] 2020-09-02 14:22
stable

Windows 10
stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc

Ubuntu 20.04 Distro WSL2
stable-x86_64-pc-windows-msvc

all with 1.46.0

**Comment by thedodd** [comment] 2020-09-02 14:23
Just in the name with helping / diagnostics, I just did a `cargo build` (for async-raft & memstore) and didn't run into any issues.

```
rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)

cargo --version
cargo 1.46.0 (149022b1d 2020-07-17)

rustup toolchain list
stable-x86_64-apple-darwin (default)
```

I wonder if this is a regression in 1.46 on some platforms ... hmmm.

**Comment by Nejat** [comment] 2020-09-02 14:26
i'll try spinning up a complete Ubuntu VM later today to try that

**Comment by thedodd** [comment] 2020-09-02 14:26
@Nejat it looks like this might be a compiler issue: https://github.com/rust-lang/rust/issues/75992#issuecomment-683255150

**Comment by Nejat** [comment] 2020-09-02 20:11
I just installed and setup an Ubuntu 20.04 VM

```cargo test``` is producing the same errors there as well

btw, ```cargo build``` builds without errors on all three of my environments:
- Windows 10
- WSL2 Ubuntu 20.04
- Ubuntu 20.04 VM

**Comment by thedodd** [comment] 2020-09-02 21:08
@Nejat ah, I had not tried the `cargo test` since updating to `rustc 1.46`, I am getting the same issue. When I do the same thing using `rustc 1.45` everything works as expected. 

I would recommend for now that you do the same thing: `rustup override set 1.45.2`. You shouldn't run into the type-length limit issue after that. 

Hopefully a `1.46.1` will be released to fix this issue soon.

**Comment by Nejat** [comment] 2020-09-03 00:07
I was able to run the tests, thanks for the help

fingers crossed on the future fix

**Closed** 2020-12-29 17:14 UTC
